# Basic site info
title:              "abhinav das •••"
description:        "stuff that goes on in my head"
keywords:           "abhinav das, personal blog, software engineer, life experience, technology and research, blockchain, ico, ico advisor, bitcoin, cryptocurrency expert, hyperledger, blockchain for business, linux foundation certified, token, token economy, assets, insuretech, computer vision, artificial intelligence, machine learning, data sciences, iot"
logo_text:          "Abhinav Das"
show_tagline:       true # edit file in /_includes/tagline.html
show_social_icons:  true # edit file in /_includes/social_links.html
og_locale:          "en_US"
cover:              "/assets/logo.png" # site image cover

# Site URL settings
url:                https://theabhinavdas.github.io # main url
baseurl:            null # for gh-pages
enforce_ssl:        theabhinavdas.github.io
github_post_dir:    https://github.com/theabhinavdas/theabhinavdas.github.io/blob/master/

# Site author info
author:
  name:             "Abhinav Das"
  email:            x at abhinav das dot com
  github_username:  theabhinavdas
  twitter_username: theabhinavdas
  facebook_url:     

# Disqus comment settings
disqus_enabled:     false
disqus_shortname:   abhinav

# Google Analytics ID
google_analytics_code: 

# Build settings
source:             ./
destination:        ./_site
permalink:          /:year/:title
markdown:           kramdown
highlighter:        rouge
timezone:           Asia/Kolkata
exclude:            ["README.md", "LICENSE.md", "CHANGELOG.md", "google9bb6a6dc60c4e360.html"]

# Site configurations
compress_html:
  clippings:        all
  comments:         ["<!-- ", " -->"]
  endings:          all
  ignore:
    envs:           [local]
  blanklines:       false
  profile:          false
  startings:        [html, head, body]

sass:
  sass_dir:         assets/scss
  style:            compressed # expanded

plugins:
  - jekyll-sitemap
